version: '3.8'

services:
  auth:
    build: ./backend/auth-service
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your-secret-key

  analysis:
    build: ./backend/analysis-service
    ports:
      - "5001:5001"
    depends_on:
      - auth

  notification:
    build: ./backend/notification-service
    ports:
      - "5002:5002"
    environment:
      - TWILIO_SID=your-sid
      - TWILIO_AUTH_TOKEN=your-token
      - TWILIO_NUMBER=+1234567890

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  api-gateway:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf